### ISSUE TITLE
java.lang.NullPointerException - CiliaQPrepMain.java:273

### ISSUE THREAD

**Issue by hansenjn** [hansenjn/CiliaQ_Preparator#3]
When running an image that is not saved, CiliaQ Preparator crashes with the error message:
```(Fiji Is Just) ImageJ 2.9.0/1.51n; Java 1.8.0_322 [64-bit]; Windows 10 10.0; 34MB of 24299MB (<1%)
 
java.lang.NullPointerException
	at ciliaQ_Prep_jnh.CiliaQPrepMain.run(CiliaQPrepMain.java:273)
	at ij.IJ.runUserPlugIn(IJ.java:217)
	at ij.IJ.runPlugIn(IJ.java:181)
	at ij.Executer.runCommand(Executer.java:137)
	at ij.Executer.run(Executer.java:66)
	at java.lang.Thread.run(Thread.java:750)
```

TODO:
Catch the error and output an interpretable message to the user explaining how the user can avoid this issue.

**Comment by hansenjn** [comment]
Issue and solution is also described in the wiki:
https://github.com/hansenjn/CiliaQ/wiki/Q&A:-How-to-solve-java.lang.NullPointerException-in-CiliaQ-Preparator%3F
